# Use root/example as user/password credentials
version: '3.1'
services:
  zswblogui:
    #please change your local version
    image: registry.cn-hangzhou.aliyuncs.com/zswblogui/zswblogui:latest-20
    restart: always
    container_name: zswblogui
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - 80:80
